Cognito form
alter-juan/frontend-arch-v1 pull request #4
Opened 2024-05-08 22:07 UTC by andresmarin0152

### ✨ Context
As a developer have a template set up to display cognito forms and also through steps tell the user what is needed.
### 🛠 Changes
- feat: Install tailwindcss
- feat: Creation of model, service, inject, etc.
- feat: Create components of view survey.
- feat: Mocks and test for the survey of views.
- feat: Add import with '@'
### 📘 Documentation

- [ ] I have updated the documentation, or
- [X] No documentation update is required

### 🧪 Test

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### 📸 Screenshots (optional)
![image](https://github.com/alter-juan/frontend-arch-v1/assets/102168079/d0fada82-a24c-44fd-bb3d-71c49162e011)
### 🪝 Git hooks
![image](https://github.com/alter-juan/frontend-arch-v1/assets/102168079/9ed758a9-a3b7-496c-89a8-81b9375c8936)

2024-05-08 22:58 UTC, EdwinFVilla commented on src/surveys/views/surveys/components/StepsTextAndNumber.vue
> +  return `w-6 h-6 border ${activeClass} border rounded-full flex justify-center items-center mr-3 text-sm lg:w-10 lg:h-10`;
> [!NOTE]
> Estas clases largas se podrian crear como un clase mas cortas
algo como esto

```css
.span--active-step {
@apply bg-[#82d39d] border-indigo-200 text-white
}
```

2024-05-08 22:58 UTC, EdwinFVilla approved these changes
<div align="center">
  <table>
    <tbody>
      <tr>
        <td align="center">
          <p>
            <a href="https://www.alternova.co/" target="_blank">
              <img
                border="0"
                width="150"
                src="https://github.com/Alternova-Inc/DFCI__MYPAINPAL__FRONTEND/assets/124185202/cad7da34-aae0-414c-916a-2e6a8d2f067c"
                alt="Alternova Logo"
              />
            </a>
          </p>
        </td>
        <td>
          <p>
            <span>Reviewed &amp; Approved | </span>
            <span><strong>Edwin Villa</strong></span>
          </p>
          <span style="white-space: nowrap">
            <span style="font-size: 12px; color: #444444">
              <img
                border="0"
                height="13"
                width="13"
                src="https://www.mail-signatures.com/signature-generator/img/templates/compact-with-large-logo/email-icon.png"
                alt="Email Icon"
              />
              &nbsp;
              <a href="mailto:edwin.villa@alternova.com" target="_blank" rel="noopener">
                <span>edwin.villa@alternova.com</span>
              </a>
            </span>
            <br />
            <span>
              <span>
                <img
                  border="0"
                  height="13"
                  width="14"
                  src="https://www.mail-signatures.com/signature-generator/img/templates/compact-with-large-logo/website-icon.png"
                  alt="Website Icon"
                />
                &nbsp;
                <a href="http://www.alternova.co" target="_blank" rel="noopener">
                  <span
                    style="
                      color: #444444;
                      font-family: Arial, sans-serif;
                      font-size: 12px;
                    "
                    >www.alternova.co</span
                  >
                </a>
              </span>
            </span>
          </span>
          <span>
            <br />
            <img
              border="0"
              width="15"
              height="13"
              src="https://www.mail-signatures.com/signature-generator/img/templates/compact-with-large-logo/address-icon.png"
              alt="Address Icon"
            />
            &nbsp; Bogotá - Colombia,
            <br />
          </span>
        </td>
      </tr>
    </tbody>
  </table>
</div>

2024-05-09 14:24 UTC, yulianasep approved these changes
<h3 align="center">Approved - Yuliana</h3>

<p align="center"><img src="https://github.com/alter-juan/frontend-arch-v1/assets/133719173/42ec7935-efe7-4b74-aef9-37b58eba2ac1"   width="200"></p>

2024-05-09 14:24 UTC, yulianasep commented on src/surveys/__test__/views/SurveysView.spec.ts
> +      it("then the user should be able to see the steps", async () => {
> [!note]
> Aquí me da la impresión de que el primer describe sobra, porque en las siguientes tres sentencias ya estas utilizando el patron given, when, then

2024-05-09 16:50 UTC, alter-juan requested changes

2024-05-09 16:50 UTC, alter-juan commented on package.json
> +    "tailwindcss": "^3.4.3",
> [!warning]
> el enfoque del template no son los estilos por lo que no veo conveniente el uso de tailwind

2024-05-09 16:50 UTC, alter-juan commented on src/routes.ts
> +});
> [!warning]
> Creo que aqui hay un tema de estilo de codigo, este cambio no afecta a cognito de forma funcional por lo que creo no es conveniente

2024-05-09 16:50 UTC, alter-juan commented on src/surveys/__test__/views/SurveysView.spec.ts
> +      it("then the user should be able to see the steps", async () => {
> [!note]
> Aqui dice que debería ver los pasos pero solo pruebas que exista uno 🤔

2024-05-09 16:50 UTC, alter-juan commented on src/surveys/services/surveys.repository.ts
> +  sendSurvey(e: EventSubmitCognitoForm): Promise<EventSubmitCognitoForm>;
> [!Caution]
> Enviar una survey no es una query, es un comando.

2024-05-09 16:50 UTC, alter-juan commented on src/surveys/services/surveys.repository.ts
> +  getSurveysByUser(): Promise<SurveyWithText[]>;
> [!note]
> Al ser del contexto de survey no veo necesario el uso de la palabra un simple `getByUser` creo que basta, sin embargo, como esta no es malo.

2024-05-09 16:50 UTC, alter-juan commented on src/surveys/surveys.routes.ts
> +      name: "HomeSurvey",
> [!important]
> es necesario crear un un centralizador de names, usualmente son enums de la siguiente forma:
```ts
export enum USER_ROUTES_NAMES {
  USER_MAIN = 'users',
  DASHBOARD = 'users-list',
  USER_DETAIL = 'user-detail',
  USER_CREATE = 'user-create',
}
```
---
```ts
export enum INSTITUTION_ROUTES_NAMES {
  INSTITUTION_MAIN = 'institution',
  INSTITUTION_INFO = 'institution-info',
  PROGRAMS = 'programs',
  WELLNESS_DATA = 'wellness-data',
  SURVEY_ANSWERS = 'survey-answers',
  INSTITUTIONS_ADMIN = 'institutions-admins',
  PROGRAMS_ADMIN = 'programs-admins',
}
```

### uso

```ts
{
      path: INSTITUTION_ROUTES_NAMES.INSTITUTION_INFO,
      name: INSTITUTION_ROUTES_NAMES.INSTITUTION_INFO,
      component: () => import(''),
}
```

2024-05-09 16:50 UTC, alter-juan commented on src/surveys/types/eventSubmitCognitoForm.ts
> +}
> [!note]
> Este no seria un modelo dto, ya que guarda información que será transferida de un punto a otro, además, de modelar a cognito? 🤔

2024-05-09 16:50 UTC, alter-juan commented on src/surveys/views/surveys/components/FormCognito.vue
> +  script.src = "https://www.cognitoforms.com/f/seamless.js";
> [!Tip]
> puede que esta url sea util como un .env, analiza si representa un riesgo de seguridad o es algo de implementación que se encuentra en la libreria.

2024-05-09 16:50 UTC, alter-juan commented on src/surveys/views/surveys/surveys.controller.ts
> +      window.location.reload();
> [!note]
> esto se hace asi porque cognito necesita este refresco o con reactividad no es suficiente?, si es asi alguien ha visto el demo para ver si es una experiencia que gusta?

2024-05-09 16:50 UTC, alter-juan commented on vite.config.ts
> +  },
> [!tip]
> Este puede ser un PR para la rama main

2024-05-24 23:02 UTC, closed without merging